apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: to-do-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/your-github-username/to-do-app.git
    targetRevision: HEAD
    path: .
    kustomize:
      namePrefix: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
