apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pvc
  template:
    metadata:
      labels:
        app: mysql-pvc
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-p1234"]
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-pvc
spec:
  selector:
    app: mysql-pvc
  ports:
    - port: 3306
      targetPort: 3306
